### ISSUE TITLE
lexicon adapter is missing the provider

### ISSUE THREAD

**Issue by balmas** [alpheios-project/client-adapters#27]
the lexicon adapter is missing the provider property. It prevents the provider from showing in the credits in the popup.

**Comment by balmas** [comment]
qa-3.0.0.51/components 1.2.17

**Comment by monzug** [comment]
that's what I see
![missing credits](https://user-images.githubusercontent.com/41396793/62547800-cb96a080-b833-11e9-86af-80b26540cf04.JPG)

**Comment by monzug** [comment]
and in panel:
![panel](https://user-images.githubusercontent.com/41396793/62547943-11536900-b834-11e9-90b5-8e3115b053f0.JPG)

**Comment by monzug** [comment]
in FF I have the following
![ff-credits](https://user-images.githubusercontent.com/41396793/62548261-858e0c80-b834-11e9-8cba-6089aa1c1ec8.JPG)

**Comment by balmas** [comment]
do you have lemma translations enabled in ff but not in chrome?

**Comment by balmas** [comment]
might also be better to test this in greek, where the definitions come from a different source than the morphology.

**Comment by monzug** [comment]
investigating. something with the build

**Comment by monzug** [comment]
you are right. Chrome had lemma set to English which is like not having lemma. is this ok??
in Greek panel I have: From A Greek-English Lexicon (Henry George Liddell, Robert Scott, Oxford, Clarendon Press, 1940), in  pop-up Morpheus and same Greek-English Lexicon

**Comment by balmas** [comment]
>Chrome had lemma set to English which is like not having lemma. @balmas, is this ok??
I think so.  We could remove English there I suppose but this setting was eventually supposed to apply to the rest of the UI too whenever we get it localized. Let's just leave it.
