### ISSUE TITLE
exclude usage examples which don't match our author/data file

### ISSUE THREAD

**Issue by monzug** [alpheios-project/client-adapters#34]
Lookup for audi then go to usage word examples. the first line does not have the work and author's name, only the line number. it should be Pseudo-Varro, Sententiae + line number.
obviously it cannot be searched by author (and work).

**Comment by balmas** [comment]
QA-3.0.1.72

**Comment by monzug** [comment]
pseudo-varro is gone (tested that Varro, Marcus Terentius is still in the authors list)
