### ISSUE TITLE
inflections with multiple lemmas share the same inflection object

### ISSUE THREAD

**Issue by balmas** [alpheios-project/client-adapters#37]
_Originally posted by @balmas in https://github.com/alpheios-project/inflection-tables/issues/114#issuecomment-445850402_

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
components 1.5.0 (qa-3.0.4.83/embed-lib 3.1.5.46)

**Comment by monzug** [comment]
so glad to see this fix in for intersum
tested in Chrome and FF and mobile
Alpheios Reading Tools 3.0.4.93
Alpheios Components 1.5.0
