### ISSUE TITLE
new client-adapter for a Concordance Service

### ISSUE THREAD

**Issue by balmas** [alpheios-project/client-adapters#4]
We need a new adapter for a remote service which will return usage examples (aka concordances) for a word.

**Adapter Interface**

**Inputs**

the adapter should take the following inputs

* Homonym (required)
* Filter Properties
* Sort Fields
* Pagination Properties

Filter Properties should be a set of key/value pairs which will identify a filter key and value
(for the moment, only 2 keys will be supported, author and work, but may expand to others in the future)

Sort Properties should be a list of sort fieldnames
(exact fields stll TBD, so this is a placeholder for now) 

Pagination Properties should be a set of key/value pairs which will identify request pagination options 
(for the moment, only 1 key, max, will be supported. may expand to others in the future)

**Outputs**

I would like to see if the output of this service could use the same WordList/WordListItem data model objects that are being developed for the Word List In Context feature (alpheios-project/components#304). 

So for the first iteration, it will return a WordList wrapped in a ResourceProvider proxy. 

**Adapter Implementation**

The first provider implementation for the adapter will be the PHI concordance service which has the following URL template:

https://latin.packhum.org/rst/concordance/{word}+[{authorId}:{workId}]{?max}

e..g https://latin.packhum.org/rst/concordance/arma[690:3]?max=5

(sort is not yet supported for the PHI Service)

The PHI service will return a JSON object which contains a list of Concordance objects with the following properties:

```
[
  {
    "link":<path to the source on the PHI site>
    "cit":<citation string for the source>
    "left":<words before the target word>
    "right":<words after the target word>
    "target":<word>
  }
]
```

Each Concordance object could be mapped to a WordListItem

left/right are the same as prefix/suffix in the W3C annotation selector terminology
target is the same as exact in the WC3 annotation selector terminology

link could be used to construct a source URL and cit can be used to present a display string for the source URL (to construct a source url from the link and cit properties in the response, you have to append the value of the cit field to the baseUrl for the service, i.e. https://latin.packhum.org . The baseUrl should be a configurable property for the adapter. )

**Mapping of Inputs for PHI**

word: The `Homonyn.targetWord` is the word to send to the service
author filter: The component which we display to the user will have unique identifiers for author and work in the format of 

urn:cts:latinLatin:phi<authorNumber>

and
urn:cts:latinLatin:phi<authorId>.phi<workId>

The PHI provider implementation can extract the PHI authorId and workId from the author and work identifiers to populate the service request.

So, for example, with the following inputs 

* Homonym object with targetWord=arma
* FilterProperties { author:"urn:cts:latinLit:phi690", work: "urn:cts:latinLit:phi003"}
* PaginationProperties { max:50 }

The URL to the PHI Service would be 

https://latin.packhum.org/rst/concordance/arma+[690:3]?max=50

And the response to the adapter API call would be a WordList containing 50 WordListItems constructed from the response.

**Comment by balmas** [comment]
The Adapter interface should also implement a separate API call which can be used to request the list of available Filter and Sort Properties and supported languages. 

This feature will only be available for Latin to start but we will expand it for other languages in the future.

I will provide a data file which contains the author and work identifiers to use to populate the filter options.   (Eventually this list may be provided by a dynamic service call and stored in a local indexedDB)

**Comment by balmas** [comment]
Here's a sample extract from a JSON file which contains a couple of authors and works in a format similar to what we will eventually use to provide the list of authors and works to make available in the UI for selection of Author and Work to filter the usage examples.  Eventually this list will come from a dynamic API call but for the first release we can just use a static JSON file because the works that are available from PHI won't change.   This is probably not the final format of the file, but it should be close enough to use for testing and development for now.  It's an object containing a list of Author objects, each of which contains a list of Work objects.  Author and Work names are in a 'title' field which is an array containing 1 or more titles and the language code (e.g. so that we can present a title in Latin, or English or French, etc.)  
The urns are what you will pull the identifiers to filter the PHI requests on, and the format of these will NOT change -- i.e. they are in the format

urn:cts:latinLit:phi[authorid].phi[workid]

In the CTS URN the author and work numbers are front-padded with 0's which need to be stripped before sending them to the PHI service

e.g. so the PHI authorid extracted from the urn urn:cts:latinLit:phi0959 is 959
e.g. so the PHI work extracted from the urn urn:cts:latinLit:phi0959.phi006 is 6

A search for arm in Ovid's Metamorphoses:
https://latin.packhum.org/rst/concordance/arma[959:6]


```
{ "authors": [
    { "urn": "urn:cts:latinLit:phi0959",
      "title": [
          { "@lang": "eng",
            "@value": "Ovid"
          }
      ],
      "works": [
        { "urn": "urn:cts:latinLit:phi0959.phi001",
          "title": [
            { "@lang":"lat",
              "@value": "Amores"
            },
            { "@lang":"eng",
              "@value": "The Art of Love"
            }
          ]
        },
        { "urn": "urn:cts:latinLit:phi0959.phi006",
          "title": [
            { "@lang":"lat",
              "@value": "Metamorphoses"
            },
            { "@lang":"eng",
              "@value": "Metamorphoses"
            },
          ]
        }
      ]
    },
    { "urn": "urn:cts:latinLit:phi0690",
      "title": [
          { "@lang": "eng",
            "@value": "Virgil"
          }
      ],
      "works": [
        { "urn": "urn:cts:latinLit:phi0690.phi003",
          "title": [
            { "@lang":"lat",
              "@value": "Aeneid"
            },
            { "@lang":"eng",
              "@value": "Aeneid"
            }
          ]
        },
      ]
    }
  ]
}
```

**Comment by irina060981** [comment]
Ok, thank you, Bridget, it is enough for now to understand format of author and work!

**Comment by balmas** [comment]
As @irina060981 points out, the PHI api does not return the Author and Title in its response with the phi numbers we are using for our author/title catalog. I.e. it has a cit field that references Cic.deOrat for phi0474.phi037.  Although there is a separate service we could use to map these, since this data isn't really going to change, I think for now we could put the abbreviations in the above author/title catalog data file as well. The client-adapter then could create a lookup hash from it that converts output from the PHI service to the urn format. E.g. maybe something like the following:

```
{ "authors": [
    { "urn": "urn:cts:latinLit:phi0959",
      "title": [
          { "@lang": "eng",
            "@value": "Ovid"
          },    
      ],
      "abbreviations: [
         { "@lang": "eng",
            "@value": "Ov."
         }
      ],
      "works": [
        { "urn": "urn:cts:latinLit:phi0959.phi001",
          "title": [
            { "@lang":"lat",
              "@value": "Amores"
            },
            { "@lang":"eng",
              "@value": "The Art of Love"
            }
          ],
          "abbreviations: [
            { "@lang": "eng",
              "@value": "Am."
           }
         ]
        },
        { "urn": "urn:cts:latinLit:phi0959.phi006",
          "title": [
            { "@lang":"lat",
              "@value": "Metamorphoses"
            },
            { "@lang":"eng",
              "@value": "Metamorphoses"
            },
          ],
          "abbreviations: [
            { "@lang": "eng",
              "@value": "Met."
            }
         ]
        }
      ]
    },
    { "urn": "urn:cts:latinLit:phi0690",
      "title": [
          { "@lang": "eng",
            "@value": "Virgil"
          }
      ],
      "abbreviations: [
         { "@lang": "eng",
            "@value": "Verg."
         }
       ],
      "works": [
        { "urn": "urn:cts:latinLit:phi0690.phi003",
          "title": [
            { "@lang":"lat",
              "@value": "Aeneid"
            },
            { "@lang":"eng",
              "@value": "Aeneid"
            }
          ],
          "abbreviations: [
           { "@lang": "eng",
            "@value": "A."
           }
         ],
        },
      ]
    }
  ]
}
```

@irina060981 what do you think?

**Comment by irina060981** [comment]
@balmas, I think, that it is a way to connect author/textWork and word usage examples.
I will implement it this way.

**Comment by irina060981** [comment]
**Realized features:**
There is a concordance adapter that has two methods: getAuthorsWorks, getWordUsageExamples.
There are options on Options tab to enable getting wordUsageExamples and max results.

Everytime LexicaQuery is executed - it checks enableWordUsageExamples option and if true, it retrieves data without filters - but with max pagination property.

Data is passed to additional tab - WordUsage tab.

**Not realized features:**
1) Sort properties - are not ready at the source
2) Output as WordItem/Wordlist - this data structure is still under development in https://github.com/alpheios-project/components/issues/304
When it will be ready, we could realize it as
> So for the first iteration, it will return a WordList wrapped in a ResourceProvider proxy
3) Authors and textWorks are uploaded from local json file, should be changed to API - are not ready at the source

**Comment by irina060981** [comment]
Update:
**Realized features:**
1.Sort properties - ready

**Not realized features:**
1. Output as WordItem/Wordlist - this data structure is still under development in alpheios-project/components#304
When it will be ready, we could realize it as

2.Authors and textWorks are uploaded from local json file, should be changed to API - are not ready at the source

@balmas , should I do anything with these two non-realized options?

**Comment by balmas** [comment]
let's leave this as is for now.
