### ISSUE TITLE
chinese prototype - add support for context forward

### ISSUE THREAD

**Issue by balmas** [alpheios-project/client-adapters#40]
the chinese adapter getHomonym method needs to accept the contextForward parameter and check for additional matches until the context is exhausted 

E.g. if the text contains

安之若素的意思

contextForward is set to 5 chars

And the word selected is 安 

the getHomonym request should have 
params.word = 安
params.contextForward = 之若素 的意

the adapter should look up 安 and add matches (2 found) on that to the result
then it should look up 安之 . it won't find results 
then it should lookup 安之若. it won't find results
then it should lookup 安之若素 and add the match (1 found) on that to the result
then it should lookup 安之若素 的 it won't find results
then it should lookup 安之若素 的意 it won't find results
being at the end of the context forward, it should return

results will contain 3 homonyms, the two found for 安 and the 1 found for 安之若素
the target word of each homonym should match the target that was actually found
so homonym 1 has target word 安
homonym 2 has target word 安
homonym 3 has target word 安之若素

**Comment by irina060981** [comment]
We need to decide about multiple homonyms first

**Comment by balmas** [comment]
closing this. will be tracked via #51
