### ISSUE TITLE
chinese adapter - pronunciation feature needs to be ordered

### ISSUE THREAD

**Issue by balmas** [alpheios-project/client-adapters#50]
The order should be:

pinyin
mandarin
cantonese
tang

ideally we would do this with an order attribute and a multi-valued feature

**Comment by kirlat** [comment]
Would that be the correct way to display pronunciation in the UI?
![image](https://user-images.githubusercontent.com/18631055/72984416-16659e00-3dfd-11ea-9155-5dda7f40d030.png)

**Comment by balmas** [comment]
yes
