### ISSUE TITLE
chinese adapter - need workaround for multiple homonyms

### ISSUE THREAD

**Issue by balmas** [alpheios-project/client-adapters#51]
We have alpheios-project/components#856 which describes a need for a refactoring to allow for multiple homonyms resulting from a lookup. This is essential for truly correct handling of the Chinese data.

That is a big undertaking, so until it is fixed, in order to proceed with testing the chinese functionality, we need an interim workaround that allows us to see the additional words found by including the context forward. 

I am open to suggestions on how to do this. In the initial quick prototype we just included them as lexemes on the original target word's homonym. 

Another approach might be to add a contextWords or some such structure to the homonym which allowed us to display the additional words for what they are more accurately without requiring the full refactoring of handling them as separate Homonym objects. 

Right now the chinese adapater code just ignores them completely because it only retrieves the original target word from the cedict service response body:

```
  _transformData (cedictEntries, targetWord) {
       .....
       cedictEntries[characterForm][targetWord].forEach(entry => {
```

**Comment by kirlat** [comment]
I like the idea of a HomonymSet superstructure proposed by @irina060981 in alpheios-project/components#856. Our current implementation of a Chinese Lexical Query involves a conditional (if language is Chinese) and we can use that to our advantage. We can add a HomonymSet structure, but use it for Chinese only.

If some components along the path support Homonym objects only (WordListController), we can, if HomonymSet is used, convert it to the more or less comparable Honomym object (take a first Homonym form the set?) as a temporary measure. Once we test a HomonymSet with Chinese we can refactor modules that use Homonym to take both Homonym and HomonymSet, and when everything will be converted, we can start using HomonymSet for other languages.

What do you think?

**Comment by balmas** [comment]
This sounds like a reasonable approach.

However, we will not really be able to begin to test the Chinese at all until we can see the multiple homonyms in the popup.  So maybe we could just add as lexemes while work on the HomonynSet proceeds?

**Comment by kirlat** [comment]
I think using an Homonym with extra lexemes is a good approach at the moment if our goal is to speed up the testing. Maybe we can just add a special prop to it to indicate this is a "pseudo-homonym", not a real one?

How would we display multiple words in a popup UI? In a tabbed UI as @irina060981 suggests, or one word below the other, or in some other way?

**Comment by balmas** [comment]
> I think using an Homonym with extra lexemes is a good approach at the moment if our goal is to speed up the testing. Maybe we can just add a special prop to it to indicate this is a "pseudo-homonym", not a real one?

Ok

> How would we display multiple words in a popup UI? In a tabbed UI as @irina060981 suggests, or one word below the other, or in some other way?

Let's keep it simple to start, and just display one word below the other. That will allow us to think about how we really want it to display.

**Comment by kirlat** [comment]
Would presenting multiple words in a popup like shown below be all right?
![image](https://user-images.githubusercontent.com/18631055/73006003-563f7c00-3e23-11ea-8583-898e25b10b59.png)
Above is the output for the `日` selection and the `月盈昃` context forward.

**Comment by balmas** [comment]
Yes, i think that looks good.
